# 가족관계 데이터 전처리

### https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=realm&dataSetSn=528

### 설치 패키지

In [1]:
# python==3.10
# pillow
# pandas
# matplotlib

### 연령/각도별 안면 데이터 저장

In [5]:
from glob import glob
import os
root_path = 'C:/Users/ypd04/OneDrive/바탕 화면/045.가족 관계가 알려진 얼굴 이미지 데이터/01.데이터/1.Training/원천데이터_0903_add/TS0001to0020/'

TS_path = os.listdir(root_path)
TS_path

['TS0001',
 'TS0002',
 'TS0003',
 'TS0004',
 'TS0005',
 'TS0006',
 'TS0007',
 'TS0008',
 'TS0009',
 'TS0010',
 'TS0011',
 'TS0012',
 'TS0013',
 'TS0014',
 'TS0015',
 'TS0016',
 'TS0017',
 'TS0018',
 'TS0019',
 'TS0020']

In [20]:
import shutil
from tqdm import tqdm

save_path = 'C:/Users/ypd04/OneDrive/바탕 화면/FamilyDatasets/'

for TS in tqdm(TS_path):
    print("TS")
    AB_path = os.listdir(root_path+TS+'/')
    if len(os.listdir(root_path+TS+'/'+'A(친가)'+'/2.Individuals'))!=0:
        image_path = glob(root_path+TS+'/'+'A(친가)'+'/2.Individuals/*.jpg')
        for image in image_path:
            if image.split("\\")[-1].find('CAM') == -1:
                shutil.copyfile(image,save_path+image.split("\\")[-1]) 
    else:
        image_path = glob(root_path+TS+'/'+'B(외가)'+'/2.Individuals/*.jpg')
        for image in image_path:
            
            if image.split("\\")[-1].find('CAM') == -1:
                shutil.copyfile(image,save_path+image.split("\\")[-1])

  5%|▌         | 1/20 [00:00<00:03,  6.17it/s]

TS
TS

 15%|█▌        | 3/20 [00:00<00:02,  7.43it/s]

TS
TS

 25%|██▌       | 5/20 [00:00<00:01,  8.11it/s]

TS
TS

 35%|███▌      | 7/20 [00:00<00:01,  8.87it/s]

TS
TS
TS

 45%|████▌     | 9/20 [00:01<00:01,  9.69it/s]

TS
TS

 60%|██████    | 12/20 [00:01<00:00,  9.28it/s]

TS
TS

 70%|███████   | 14/20 [00:01<00:00,  8.34it/s]

TS
TS

 80%|████████  | 16/20 [00:01<00:00,  8.50it/s]

TS
TS

 90%|█████████ | 18/20 [00:02<00:00,  8.40it/s]

TS
TS

100%|██████████| 20/20 [00:02<00:00,  8.64it/s]

TS

### Multi Label Classification을 위한 DataFrame 화

In [79]:
import pandas as pd

df = pd.DataFrame(columns=['img_path','M','F',"10's","20's","30's","40's","50's","60+"])
df

Empty DataFrame
Columns: [img_path, M, F, 10's, 20's, 30's, 40's, 50's, 60+]
Index: []

In [80]:
save_path = 'C:/Users/ypd04/OneDrive/바탕 화면/FamilyDatasets/'

datasets = glob(save_path+'*.jpg')
datasets[:5]

['C:/Users/ypd04/OneDrive/바탕 화면/FamilyDatasets\\F0001_IND_D_18_-45_01.JPG',
 'C:/Users/ypd04/OneDrive/바탕 화면/FamilyDatasets\\F0001_IND_D_18_-45_02.JPG',
 'C:/Users/ypd04/OneDrive/바탕 화면/FamilyDatasets\\F0001_IND_D_18_-45_03.JPG',
 'C:/Users/ypd04/OneDrive/바탕 화면/FamilyDatasets\\F0001_IND_D_18_-45_04.JPG',
 'C:/Users/ypd04/OneDrive/바탕 화면/FamilyDatasets\\F0001_IND_D_18_-90_01.JPG']

In [81]:
img_paths = []
for data in datasets:
    img_path = data.split("\\")[-1]
    img_paths.append(img_path)
# img_paths

df['img_path'] = img_paths
df

                       img_path    M    F 10's 20's 30's 40's 50's  60+
0     F0001_IND_D_18_-45_01.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1     F0001_IND_D_18_-45_02.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2     F0001_IND_D_18_-45_03.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3     F0001_IND_D_18_-45_04.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4     F0001_IND_D_18_-90_01.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...                         ...  ...  ...  ...  ...  ...  ...  ...  ...
1255   F0020_IND_S_12_45_04.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1256   F0020_IND_S_12_90_01.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1257   F0020_IND_S_12_90_02.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1258   F0020_IND_S_12_90_03.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1259   F0020_IND_S_12_90_04.JPG  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[1260 rows x 9 columns]

In [82]:
# columns

img_paths = []
gender_M = []
gender_F = []
age_20 = []
age_30 = []
age_40 = []
age_50 = []
age_60 = []

gender_M_list = ['GF','F','S']
gender_F_list = ['GM','M','D']

In [83]:
for idx,data in enumerate(datasets):
    label = data.split("\\")[-1]
    img_paths.append(label)

    gender = label.split('_')[2]
    age = int(label.split('_')[3])
    print(age)

    if gender in gender_M_list:
        df.loc[idx,'M'] = 1
    else:
        df.loc[idx,'F'] = 1

    if age>=10 and age<20:
        df.loc[idx,"10's"] = 1
    elif age>=20 and age<30:
        df.loc[idx,"20's"] = 1
    elif age>=30 and age<40:
        df.loc[idx,"30's"] = 1
    elif age>=40 and age<50:
        df.loc[idx,"40's"] = 1
    elif age>=50 and age<60:
        df.loc[idx,"50's"] = 1
    elif age>=60:
        df.loc[idx,"60+"] = 1

18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
42
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
84
84
84
84
84
84
84
84
84
84
84
84
84
84
84
84
84
84
84
84
84
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12

In [84]:
df

                       img_path    M    F 10's 20's 30's 40's 50's  60+
0     F0001_IND_D_18_-45_01.JPG  NaN    1    1  NaN  NaN  NaN  NaN  NaN
1     F0001_IND_D_18_-45_02.JPG  NaN    1    1  NaN  NaN  NaN  NaN  NaN
2     F0001_IND_D_18_-45_03.JPG  NaN    1    1  NaN  NaN  NaN  NaN  NaN
3     F0001_IND_D_18_-45_04.JPG  NaN    1    1  NaN  NaN  NaN  NaN  NaN
4     F0001_IND_D_18_-90_01.JPG  NaN    1    1  NaN  NaN  NaN  NaN  NaN
...                         ...  ...  ...  ...  ...  ...  ...  ...  ...
1255   F0020_IND_S_12_45_04.JPG    1  NaN    1  NaN  NaN  NaN  NaN  NaN
1256   F0020_IND_S_12_90_01.JPG    1  NaN    1  NaN  NaN  NaN  NaN  NaN
1257   F0020_IND_S_12_90_02.JPG    1  NaN    1  NaN  NaN  NaN  NaN  NaN
1258   F0020_IND_S_12_90_03.JPG    1  NaN    1  NaN  NaN  NaN  NaN  NaN
1259   F0020_IND_S_12_90_04.JPG    1  NaN    1  NaN  NaN  NaN  NaN  NaN

[1260 rows x 9 columns]

In [87]:
df = df.fillna(0)
df

                       img_path  M  F  10's  20's  30's  40's  50's  60+
0     F0001_IND_D_18_-45_01.JPG  0  1     1     0     0     0     0    0
1     F0001_IND_D_18_-45_02.JPG  0  1     1     0     0     0     0    0
2     F0001_IND_D_18_-45_03.JPG  0  1     1     0     0     0     0    0
3     F0001_IND_D_18_-45_04.JPG  0  1     1     0     0     0     0    0
4     F0001_IND_D_18_-90_01.JPG  0  1     1     0     0     0     0    0
...                         ... .. ..   ...   ...   ...   ...   ...  ...
1255   F0020_IND_S_12_45_04.JPG  1  0     1     0     0     0     0    0
1256   F0020_IND_S_12_90_01.JPG  1  0     1     0     0     0     0    0
1257   F0020_IND_S_12_90_02.JPG  1  0     1     0     0     0     0    0
1258   F0020_IND_S_12_90_03.JPG  1  0     1     0     0     0     0    0
1259   F0020_IND_S_12_90_04.JPG  1  0     1     0     0     0     0    0

[1260 rows x 9 columns]

### 데이터프레임 확인

In [88]:
df.sample(20)

                       img_path  M  F  10's  20's  30's  40's  50's  60+
1069   F0017_IND_S_13_90_03.JPG  1  0     1     0     0     0     0    0
585    F0010_IND_F_46_90_02.JPG  1  0     0     0     0     1     0    0
340   F0006_IND_F_42_-90_01.JPG  1  0     0     0     0     1     0    0
1210  F0020_IND_GM_70_45_01.JPG  0  1     0     0     0     0     0    1
833    F0014_IND_D_14_45_02.JPG  0  1     1     0     0     0     0    0
1129   F0018_IND_S_12_45_04.JPG  1  0     1     0     0     0     0    0
384   F0007_IND_F_48_-90_03.JPG  1  0     0     0     0     1     0    0
520   F0009_IND_GM_84_45_04.JPG  0  1     0     0     0     0     0    1
226   F0004_IND_GM_68_45_04.JPG  0  1     0     0     0     0     0    1
661     F0011_IND_F_46_0_03.JPG  1  0     0     0     0     1     0    0
557     F0009_IND_S_30_0_04.JPG  1  0     0     0     1     0     0    0
203    F0004_IND_D_12_45_02.JPG  0  1     1     0     0     0     0    0
111   F0002_IND_S_16_-90_03.JPG  1  0     1     0     0     0     0    0
120    F0002_IND_S_16_45_03.JPG  1  0     1     0     0     0     0    0
394    F0007_IND_F_48_45_04.JPG  1  0     0     0     0     1     0    0
1096  F0018_IND_M_43_-90_01.JPG  0  1     0     0     0     1     0    0
1161  F0019_IND_M_43_-90_03.JPG  0  1     0     0     0     1     0    0
1185    F0019_IND_S_13_0_02.JPG  1  0     1     0     0     0     0    0
746     F0012_IND_S_18_0_04.JPG  1  0     1     0     0     0     0    0
127   F0003_IND_D_14_-45_02.JPG  0  1     1     0     0     0     0    0